### PR TITLE
Oauth2

### PR DESCRIPTION
**Pull request by zzk**
Implement `oauth2 token based authorization` into `ruby_odata`. Heavily depends on #58.

### CODE REVIEW

**Comment by exadeci** [comment]
Any update on that ?

**Comment by visoft** [comment]
This was released as v0.2.0.beta. There are some bugs still in it. I'm hoping to have time to work on this in the near future. If you have time and are willing to add a PR, that would be awesome!

**Comment by exadeci** [comment]
It doesn't seems to work with https://msdn.microsoft.com/en-us/library/mt593051.aspx for some reason it can't parse it  `Nokogiri::XML::XPath::SyntaxError: Undefined namespace prefix: edmx:Edmx/edmx:DataServices/*` so I guess I won't be using it.

**Comment by visoft** [comment]
It looks like that's OData version 4. Currently ruby_odata doesn't support 4.0, but I'd love to change that.

**Comment by wtfiwtz** [comment]
After a lot of trouble I got access to Dynamics 365 on Azure Active Directory through the Web API and oauth2 authentication... 

https://github.com/AzureAD/azure-activedirectory-library-for-ruby

With the secret sauce...

```
username      = 'admin@tenant.onmicrosoft.com'
password      = 'xxxxxxxxxxxx'
client_id     = 'xxxxx-xxxx-xxx-xxxxxx-xxxxxxx'
client_secret = 'xxxXXXxxXXXxxxXXXxxXXXXXXXXxxxxxx='
tenant        = 'tenant.onmicrosoft.com'
user_cred     = ADAL::UserCredential.new(username, password)
client_cred   = ADAL::ClientCredential.new(client_id, client_secret)
context       = ADAL::AuthenticationContext.new(ADAL::Authority::WORLD_WIDE_AUTHORITY, tenant)
resource      = "https://graph.microsoft.com"
tokens        = context.acquire_token_for_user(resource, client_cred, user_cred)

# add the access token to the request header
callback = Proc.new { |r| r.headers["Authorization"] = "Bearer #{tokens.access_token}" }
```

Microsoft has some ODATA v4 suppport implemented here:
https://github.com/microsoftgraph/msgraph-sdk-ruby

Not sure if I will use this for Dynamics 365 though... but at least I got past the oauth 2.0 hurdles.

**Comment by wtfiwtz** [comment]
For the SOAP API (instead of Web API) on Dynamics you can use this library too: https://github.com/exadeci/dynamics_crm

**Comment by exadeci** [comment]
@wtfiwtz It should be the parent repository https://github.com/TinderBox/dynamics_crm the one you've linked is mine with a custom change.

**Comment by wtfiwtz** [comment]
Thanks @exadeci... I meant to link the parent but did that one accidentally!

**Pull request closed without merging**
